// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
	"time"

	resource "github.com/telia-oss/github-pr-resource"
	"github.com/telia-oss/github-pr-resource/pullrequest"
)

type FakeGithub struct {
	GetChangedFilesStub        func(int) ([]string, error)
	getChangedFilesMutex       sync.RWMutex
	getChangedFilesArgsForCall []struct {
		arg1 int
	}
	getChangedFilesReturns struct {
		result1 []string
		result2 error
	}
	getChangedFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetLatestOpenPullRequestStub        func() ([]pullrequest.PullRequest, error)
	getLatestOpenPullRequestMutex       sync.RWMutex
	getLatestOpenPullRequestArgsForCall []struct {
	}
	getLatestOpenPullRequestReturns struct {
		result1 []pullrequest.PullRequest
		result2 error
	}
	getLatestOpenPullRequestReturnsOnCall map[int]struct {
		result1 []pullrequest.PullRequest
		result2 error
	}
	GetPullRequestStub        func(int, string) (pullrequest.PullRequest, error)
	getPullRequestMutex       sync.RWMutex
	getPullRequestArgsForCall []struct {
		arg1 int
		arg2 string
	}
	getPullRequestReturns struct {
		result1 pullrequest.PullRequest
		result2 error
	}
	getPullRequestReturnsOnCall map[int]struct {
		result1 pullrequest.PullRequest
		result2 error
	}
	ListOpenPullRequestsStub        func(time.Time) ([]pullrequest.PullRequest, error)
	listOpenPullRequestsMutex       sync.RWMutex
	listOpenPullRequestsArgsForCall []struct {
		arg1 time.Time
	}
	listOpenPullRequestsReturns struct {
		result1 []pullrequest.PullRequest
		result2 error
	}
	listOpenPullRequestsReturnsOnCall map[int]struct {
		result1 []pullrequest.PullRequest
		result2 error
	}
	PostCommentStub        func(int, string) error
	postCommentMutex       sync.RWMutex
	postCommentArgsForCall []struct {
		arg1 int
		arg2 string
	}
	postCommentReturns struct {
		result1 error
	}
	postCommentReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateCommitStatusStub        func(string, string, string, string, string, string) error
	updateCommitStatusMutex       sync.RWMutex
	updateCommitStatusArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
	}
	updateCommitStatusReturns struct {
		result1 error
	}
	updateCommitStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGithub) GetChangedFiles(arg1 int) ([]string, error) {
	fake.getChangedFilesMutex.Lock()
	ret, specificReturn := fake.getChangedFilesReturnsOnCall[len(fake.getChangedFilesArgsForCall)]
	fake.getChangedFilesArgsForCall = append(fake.getChangedFilesArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("GetChangedFiles", []interface{}{arg1})
	fake.getChangedFilesMutex.Unlock()
	if fake.GetChangedFilesStub != nil {
		return fake.GetChangedFilesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getChangedFilesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithub) GetChangedFilesCallCount() int {
	fake.getChangedFilesMutex.RLock()
	defer fake.getChangedFilesMutex.RUnlock()
	return len(fake.getChangedFilesArgsForCall)
}

func (fake *FakeGithub) GetChangedFilesCalls(stub func(int) ([]string, error)) {
	fake.getChangedFilesMutex.Lock()
	defer fake.getChangedFilesMutex.Unlock()
	fake.GetChangedFilesStub = stub
}

func (fake *FakeGithub) GetChangedFilesArgsForCall(i int) int {
	fake.getChangedFilesMutex.RLock()
	defer fake.getChangedFilesMutex.RUnlock()
	argsForCall := fake.getChangedFilesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGithub) GetChangedFilesReturns(result1 []string, result2 error) {
	fake.getChangedFilesMutex.Lock()
	defer fake.getChangedFilesMutex.Unlock()
	fake.GetChangedFilesStub = nil
	fake.getChangedFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) GetChangedFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.getChangedFilesMutex.Lock()
	defer fake.getChangedFilesMutex.Unlock()
	fake.GetChangedFilesStub = nil
	if fake.getChangedFilesReturnsOnCall == nil {
		fake.getChangedFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getChangedFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) GetLatestOpenPullRequest() ([]pullrequest.PullRequest, error) {
	fake.getLatestOpenPullRequestMutex.Lock()
	ret, specificReturn := fake.getLatestOpenPullRequestReturnsOnCall[len(fake.getLatestOpenPullRequestArgsForCall)]
	fake.getLatestOpenPullRequestArgsForCall = append(fake.getLatestOpenPullRequestArgsForCall, struct {
	}{})
	fake.recordInvocation("GetLatestOpenPullRequest", []interface{}{})
	fake.getLatestOpenPullRequestMutex.Unlock()
	if fake.GetLatestOpenPullRequestStub != nil {
		return fake.GetLatestOpenPullRequestStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getLatestOpenPullRequestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithub) GetLatestOpenPullRequestCallCount() int {
	fake.getLatestOpenPullRequestMutex.RLock()
	defer fake.getLatestOpenPullRequestMutex.RUnlock()
	return len(fake.getLatestOpenPullRequestArgsForCall)
}

func (fake *FakeGithub) GetLatestOpenPullRequestCalls(stub func() ([]pullrequest.PullRequest, error)) {
	fake.getLatestOpenPullRequestMutex.Lock()
	defer fake.getLatestOpenPullRequestMutex.Unlock()
	fake.GetLatestOpenPullRequestStub = stub
}

func (fake *FakeGithub) GetLatestOpenPullRequestReturns(result1 []pullrequest.PullRequest, result2 error) {
	fake.getLatestOpenPullRequestMutex.Lock()
	defer fake.getLatestOpenPullRequestMutex.Unlock()
	fake.GetLatestOpenPullRequestStub = nil
	fake.getLatestOpenPullRequestReturns = struct {
		result1 []pullrequest.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) GetLatestOpenPullRequestReturnsOnCall(i int, result1 []pullrequest.PullRequest, result2 error) {
	fake.getLatestOpenPullRequestMutex.Lock()
	defer fake.getLatestOpenPullRequestMutex.Unlock()
	fake.GetLatestOpenPullRequestStub = nil
	if fake.getLatestOpenPullRequestReturnsOnCall == nil {
		fake.getLatestOpenPullRequestReturnsOnCall = make(map[int]struct {
			result1 []pullrequest.PullRequest
			result2 error
		})
	}
	fake.getLatestOpenPullRequestReturnsOnCall[i] = struct {
		result1 []pullrequest.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) GetPullRequest(arg1 int, arg2 string) (pullrequest.PullRequest, error) {
	fake.getPullRequestMutex.Lock()
	ret, specificReturn := fake.getPullRequestReturnsOnCall[len(fake.getPullRequestArgsForCall)]
	fake.getPullRequestArgsForCall = append(fake.getPullRequestArgsForCall, struct {
		arg1 int
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("GetPullRequest", []interface{}{arg1, arg2})
	fake.getPullRequestMutex.Unlock()
	if fake.GetPullRequestStub != nil {
		return fake.GetPullRequestStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getPullRequestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithub) GetPullRequestCallCount() int {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	return len(fake.getPullRequestArgsForCall)
}

func (fake *FakeGithub) GetPullRequestCalls(stub func(int, string) (pullrequest.PullRequest, error)) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = stub
}

func (fake *FakeGithub) GetPullRequestArgsForCall(i int) (int, string) {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	argsForCall := fake.getPullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithub) GetPullRequestReturns(result1 pullrequest.PullRequest, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	fake.getPullRequestReturns = struct {
		result1 pullrequest.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) GetPullRequestReturnsOnCall(i int, result1 pullrequest.PullRequest, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	if fake.getPullRequestReturnsOnCall == nil {
		fake.getPullRequestReturnsOnCall = make(map[int]struct {
			result1 pullrequest.PullRequest
			result2 error
		})
	}
	fake.getPullRequestReturnsOnCall[i] = struct {
		result1 pullrequest.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) ListOpenPullRequests(arg1 time.Time) ([]pullrequest.PullRequest, error) {
	fake.listOpenPullRequestsMutex.Lock()
	ret, specificReturn := fake.listOpenPullRequestsReturnsOnCall[len(fake.listOpenPullRequestsArgsForCall)]
	fake.listOpenPullRequestsArgsForCall = append(fake.listOpenPullRequestsArgsForCall, struct {
		arg1 time.Time
	}{arg1})
	fake.recordInvocation("ListOpenPullRequests", []interface{}{arg1})
	fake.listOpenPullRequestsMutex.Unlock()
	if fake.ListOpenPullRequestsStub != nil {
		return fake.ListOpenPullRequestsStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listOpenPullRequestsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithub) ListOpenPullRequestsCallCount() int {
	fake.listOpenPullRequestsMutex.RLock()
	defer fake.listOpenPullRequestsMutex.RUnlock()
	return len(fake.listOpenPullRequestsArgsForCall)
}

func (fake *FakeGithub) ListOpenPullRequestsCalls(stub func(time.Time) ([]pullrequest.PullRequest, error)) {
	fake.listOpenPullRequestsMutex.Lock()
	defer fake.listOpenPullRequestsMutex.Unlock()
	fake.ListOpenPullRequestsStub = stub
}

func (fake *FakeGithub) ListOpenPullRequestsArgsForCall(i int) time.Time {
	fake.listOpenPullRequestsMutex.RLock()
	defer fake.listOpenPullRequestsMutex.RUnlock()
	argsForCall := fake.listOpenPullRequestsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGithub) ListOpenPullRequestsReturns(result1 []pullrequest.PullRequest, result2 error) {
	fake.listOpenPullRequestsMutex.Lock()
	defer fake.listOpenPullRequestsMutex.Unlock()
	fake.ListOpenPullRequestsStub = nil
	fake.listOpenPullRequestsReturns = struct {
		result1 []pullrequest.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) ListOpenPullRequestsReturnsOnCall(i int, result1 []pullrequest.PullRequest, result2 error) {
	fake.listOpenPullRequestsMutex.Lock()
	defer fake.listOpenPullRequestsMutex.Unlock()
	fake.ListOpenPullRequestsStub = nil
	if fake.listOpenPullRequestsReturnsOnCall == nil {
		fake.listOpenPullRequestsReturnsOnCall = make(map[int]struct {
			result1 []pullrequest.PullRequest
			result2 error
		})
	}
	fake.listOpenPullRequestsReturnsOnCall[i] = struct {
		result1 []pullrequest.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) PostComment(arg1 int, arg2 string) error {
	fake.postCommentMutex.Lock()
	ret, specificReturn := fake.postCommentReturnsOnCall[len(fake.postCommentArgsForCall)]
	fake.postCommentArgsForCall = append(fake.postCommentArgsForCall, struct {
		arg1 int
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("PostComment", []interface{}{arg1, arg2})
	fake.postCommentMutex.Unlock()
	if fake.PostCommentStub != nil {
		return fake.PostCommentStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.postCommentReturns
	return fakeReturns.result1
}

func (fake *FakeGithub) PostCommentCallCount() int {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	return len(fake.postCommentArgsForCall)
}

func (fake *FakeGithub) PostCommentCalls(stub func(int, string) error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = stub
}

func (fake *FakeGithub) PostCommentArgsForCall(i int) (int, string) {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	argsForCall := fake.postCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithub) PostCommentReturns(result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	fake.postCommentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) PostCommentReturnsOnCall(i int, result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	if fake.postCommentReturnsOnCall == nil {
		fake.postCommentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postCommentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) UpdateCommitStatus(arg1 string, arg2 string, arg3 string, arg4 string, arg5 string, arg6 string) error {
	fake.updateCommitStatusMutex.Lock()
	ret, specificReturn := fake.updateCommitStatusReturnsOnCall[len(fake.updateCommitStatusArgsForCall)]
	fake.updateCommitStatusArgsForCall = append(fake.updateCommitStatusArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.recordInvocation("UpdateCommitStatus", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.updateCommitStatusMutex.Unlock()
	if fake.UpdateCommitStatusStub != nil {
		return fake.UpdateCommitStatusStub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateCommitStatusReturns
	return fakeReturns.result1
}

func (fake *FakeGithub) UpdateCommitStatusCallCount() int {
	fake.updateCommitStatusMutex.RLock()
	defer fake.updateCommitStatusMutex.RUnlock()
	return len(fake.updateCommitStatusArgsForCall)
}

func (fake *FakeGithub) UpdateCommitStatusCalls(stub func(string, string, string, string, string, string) error) {
	fake.updateCommitStatusMutex.Lock()
	defer fake.updateCommitStatusMutex.Unlock()
	fake.UpdateCommitStatusStub = stub
}

func (fake *FakeGithub) UpdateCommitStatusArgsForCall(i int) (string, string, string, string, string, string) {
	fake.updateCommitStatusMutex.RLock()
	defer fake.updateCommitStatusMutex.RUnlock()
	argsForCall := fake.updateCommitStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeGithub) UpdateCommitStatusReturns(result1 error) {
	fake.updateCommitStatusMutex.Lock()
	defer fake.updateCommitStatusMutex.Unlock()
	fake.UpdateCommitStatusStub = nil
	fake.updateCommitStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) UpdateCommitStatusReturnsOnCall(i int, result1 error) {
	fake.updateCommitStatusMutex.Lock()
	defer fake.updateCommitStatusMutex.Unlock()
	fake.UpdateCommitStatusStub = nil
	if fake.updateCommitStatusReturnsOnCall == nil {
		fake.updateCommitStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateCommitStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getChangedFilesMutex.RLock()
	defer fake.getChangedFilesMutex.RUnlock()
	fake.getLatestOpenPullRequestMutex.RLock()
	defer fake.getLatestOpenPullRequestMutex.RUnlock()
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	fake.listOpenPullRequestsMutex.RLock()
	defer fake.listOpenPullRequestsMutex.RUnlock()
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	fake.updateCommitStatusMutex.RLock()
	defer fake.updateCommitStatusMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGithub) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resource.Github = new(FakeGithub)
