// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	resource "github.com/telia-oss/github-pr-resource"
)

type FakeGithub struct {
	GetPullRequestStub        func(string, string) (*resource.PullRequest, error)
	getPullRequestMutex       sync.RWMutex
	getPullRequestArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getPullRequestReturns struct {
		result1 *resource.PullRequest
		result2 error
	}
	getPullRequestReturnsOnCall map[int]struct {
		result1 *resource.PullRequest
		result2 error
	}
	ListModifiedFilesStub        func(int) ([]string, error)
	listModifiedFilesMutex       sync.RWMutex
	listModifiedFilesArgsForCall []struct {
		arg1 int
	}
	listModifiedFilesReturns struct {
		result1 []string
		result2 error
	}
	listModifiedFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ListOpenPullRequestsStub        func() ([]*resource.PullRequest, error)
	listOpenPullRequestsMutex       sync.RWMutex
	listOpenPullRequestsArgsForCall []struct {
	}
	listOpenPullRequestsReturns struct {
		result1 []*resource.PullRequest
		result2 error
	}
	listOpenPullRequestsReturnsOnCall map[int]struct {
		result1 []*resource.PullRequest
		result2 error
	}
	PostCommentStub        func(string, string) error
	postCommentMutex       sync.RWMutex
	postCommentArgsForCall []struct {
		arg1 string
		arg2 string
	}
	postCommentReturns struct {
		result1 error
	}
	postCommentReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateCommitStatusStub        func(string, string, string) error
	updateCommitStatusMutex       sync.RWMutex
	updateCommitStatusArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	updateCommitStatusReturns struct {
		result1 error
	}
	updateCommitStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGithub) GetPullRequest(arg1 string, arg2 string) (*resource.PullRequest, error) {
	fake.getPullRequestMutex.Lock()
	ret, specificReturn := fake.getPullRequestReturnsOnCall[len(fake.getPullRequestArgsForCall)]
	fake.getPullRequestArgsForCall = append(fake.getPullRequestArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("GetPullRequest", []interface{}{arg1, arg2})
	fake.getPullRequestMutex.Unlock()
	if fake.GetPullRequestStub != nil {
		return fake.GetPullRequestStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getPullRequestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithub) GetPullRequestCallCount() int {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	return len(fake.getPullRequestArgsForCall)
}

func (fake *FakeGithub) GetPullRequestCalls(stub func(string, string) (*resource.PullRequest, error)) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = stub
}

func (fake *FakeGithub) GetPullRequestArgsForCall(i int) (string, string) {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	argsForCall := fake.getPullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithub) GetPullRequestReturns(result1 *resource.PullRequest, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	fake.getPullRequestReturns = struct {
		result1 *resource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) GetPullRequestReturnsOnCall(i int, result1 *resource.PullRequest, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	if fake.getPullRequestReturnsOnCall == nil {
		fake.getPullRequestReturnsOnCall = make(map[int]struct {
			result1 *resource.PullRequest
			result2 error
		})
	}
	fake.getPullRequestReturnsOnCall[i] = struct {
		result1 *resource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) ListModifiedFiles(arg1 int) ([]string, error) {
	fake.listModifiedFilesMutex.Lock()
	ret, specificReturn := fake.listModifiedFilesReturnsOnCall[len(fake.listModifiedFilesArgsForCall)]
	fake.listModifiedFilesArgsForCall = append(fake.listModifiedFilesArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("ListModifiedFiles", []interface{}{arg1})
	fake.listModifiedFilesMutex.Unlock()
	if fake.ListModifiedFilesStub != nil {
		return fake.ListModifiedFilesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listModifiedFilesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithub) ListModifiedFilesCallCount() int {
	fake.listModifiedFilesMutex.RLock()
	defer fake.listModifiedFilesMutex.RUnlock()
	return len(fake.listModifiedFilesArgsForCall)
}

func (fake *FakeGithub) ListModifiedFilesCalls(stub func(int) ([]string, error)) {
	fake.listModifiedFilesMutex.Lock()
	defer fake.listModifiedFilesMutex.Unlock()
	fake.ListModifiedFilesStub = stub
}

func (fake *FakeGithub) ListModifiedFilesArgsForCall(i int) int {
	fake.listModifiedFilesMutex.RLock()
	defer fake.listModifiedFilesMutex.RUnlock()
	argsForCall := fake.listModifiedFilesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGithub) ListModifiedFilesReturns(result1 []string, result2 error) {
	fake.listModifiedFilesMutex.Lock()
	defer fake.listModifiedFilesMutex.Unlock()
	fake.ListModifiedFilesStub = nil
	fake.listModifiedFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) ListModifiedFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listModifiedFilesMutex.Lock()
	defer fake.listModifiedFilesMutex.Unlock()
	fake.ListModifiedFilesStub = nil
	if fake.listModifiedFilesReturnsOnCall == nil {
		fake.listModifiedFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listModifiedFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) ListOpenPullRequests() ([]*resource.PullRequest, error) {
	fake.listOpenPullRequestsMutex.Lock()
	ret, specificReturn := fake.listOpenPullRequestsReturnsOnCall[len(fake.listOpenPullRequestsArgsForCall)]
	fake.listOpenPullRequestsArgsForCall = append(fake.listOpenPullRequestsArgsForCall, struct {
	}{})
	fake.recordInvocation("ListOpenPullRequests", []interface{}{})
	fake.listOpenPullRequestsMutex.Unlock()
	if fake.ListOpenPullRequestsStub != nil {
		return fake.ListOpenPullRequestsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listOpenPullRequestsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGithub) ListOpenPullRequestsCallCount() int {
	fake.listOpenPullRequestsMutex.RLock()
	defer fake.listOpenPullRequestsMutex.RUnlock()
	return len(fake.listOpenPullRequestsArgsForCall)
}

func (fake *FakeGithub) ListOpenPullRequestsCalls(stub func() ([]*resource.PullRequest, error)) {
	fake.listOpenPullRequestsMutex.Lock()
	defer fake.listOpenPullRequestsMutex.Unlock()
	fake.ListOpenPullRequestsStub = stub
}

func (fake *FakeGithub) ListOpenPullRequestsReturns(result1 []*resource.PullRequest, result2 error) {
	fake.listOpenPullRequestsMutex.Lock()
	defer fake.listOpenPullRequestsMutex.Unlock()
	fake.ListOpenPullRequestsStub = nil
	fake.listOpenPullRequestsReturns = struct {
		result1 []*resource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) ListOpenPullRequestsReturnsOnCall(i int, result1 []*resource.PullRequest, result2 error) {
	fake.listOpenPullRequestsMutex.Lock()
	defer fake.listOpenPullRequestsMutex.Unlock()
	fake.ListOpenPullRequestsStub = nil
	if fake.listOpenPullRequestsReturnsOnCall == nil {
		fake.listOpenPullRequestsReturnsOnCall = make(map[int]struct {
			result1 []*resource.PullRequest
			result2 error
		})
	}
	fake.listOpenPullRequestsReturnsOnCall[i] = struct {
		result1 []*resource.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGithub) PostComment(arg1 string, arg2 string) error {
	fake.postCommentMutex.Lock()
	ret, specificReturn := fake.postCommentReturnsOnCall[len(fake.postCommentArgsForCall)]
	fake.postCommentArgsForCall = append(fake.postCommentArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("PostComment", []interface{}{arg1, arg2})
	fake.postCommentMutex.Unlock()
	if fake.PostCommentStub != nil {
		return fake.PostCommentStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.postCommentReturns
	return fakeReturns.result1
}

func (fake *FakeGithub) PostCommentCallCount() int {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	return len(fake.postCommentArgsForCall)
}

func (fake *FakeGithub) PostCommentCalls(stub func(string, string) error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = stub
}

func (fake *FakeGithub) PostCommentArgsForCall(i int) (string, string) {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	argsForCall := fake.postCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGithub) PostCommentReturns(result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	fake.postCommentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) PostCommentReturnsOnCall(i int, result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	if fake.postCommentReturnsOnCall == nil {
		fake.postCommentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postCommentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) UpdateCommitStatus(arg1 string, arg2 string, arg3 string) error {
	fake.updateCommitStatusMutex.Lock()
	ret, specificReturn := fake.updateCommitStatusReturnsOnCall[len(fake.updateCommitStatusArgsForCall)]
	fake.updateCommitStatusArgsForCall = append(fake.updateCommitStatusArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("UpdateCommitStatus", []interface{}{arg1, arg2, arg3})
	fake.updateCommitStatusMutex.Unlock()
	if fake.UpdateCommitStatusStub != nil {
		return fake.UpdateCommitStatusStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateCommitStatusReturns
	return fakeReturns.result1
}

func (fake *FakeGithub) UpdateCommitStatusCallCount() int {
	fake.updateCommitStatusMutex.RLock()
	defer fake.updateCommitStatusMutex.RUnlock()
	return len(fake.updateCommitStatusArgsForCall)
}

func (fake *FakeGithub) UpdateCommitStatusCalls(stub func(string, string, string) error) {
	fake.updateCommitStatusMutex.Lock()
	defer fake.updateCommitStatusMutex.Unlock()
	fake.UpdateCommitStatusStub = stub
}

func (fake *FakeGithub) UpdateCommitStatusArgsForCall(i int) (string, string, string) {
	fake.updateCommitStatusMutex.RLock()
	defer fake.updateCommitStatusMutex.RUnlock()
	argsForCall := fake.updateCommitStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGithub) UpdateCommitStatusReturns(result1 error) {
	fake.updateCommitStatusMutex.Lock()
	defer fake.updateCommitStatusMutex.Unlock()
	fake.UpdateCommitStatusStub = nil
	fake.updateCommitStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) UpdateCommitStatusReturnsOnCall(i int, result1 error) {
	fake.updateCommitStatusMutex.Lock()
	defer fake.updateCommitStatusMutex.Unlock()
	fake.UpdateCommitStatusStub = nil
	if fake.updateCommitStatusReturnsOnCall == nil {
		fake.updateCommitStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateCommitStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGithub) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	fake.listModifiedFilesMutex.RLock()
	defer fake.listModifiedFilesMutex.RUnlock()
	fake.listOpenPullRequestsMutex.RLock()
	defer fake.listOpenPullRequestsMutex.RUnlock()
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	fake.updateCommitStatusMutex.RLock()
	defer fake.updateCommitStatusMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGithub) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resource.Github = new(FakeGithub)
